[Window]
Top=181
Left=103
Width=1478
Height=820
State=Normal

; HaYTooL Firewall Kategori & Ayar Yapilandirmasi (HaYTooL_Firewall.ini)
; Bu dosya insanca okunabilir formatta yazilmistir. Elle de duzenleyebilirsiniz.

[Settings]
FullSafeMode=False
Language=TR
GitHub=ENC:AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA+DF4uwUr1k6WBsA+IxICKgAAAAACAAAAAAAQZgAAAAEAACAAAADRyhy68MzlHlJVTENKyV2tnWwad+vJz7QGVeU2Bb56tQAAAAAOgAAAAAIAACAAAABCkR/jkcwYH+k6eVw7EJrLdEpdAOgWx1x79fd3jz3YhzAAAACKifRda5e/7kBKNl023BJTI6rrpFL6bVGdtpatEkiSwTHZ7CyhlNsrbWWgWZ9+w4lAAAAAye6MJRNtOSkp45EBpdWcG3vZBkuzCUZFRIIqPCtNUTk7T03Y49/XtB0o0+6TfkU/d0N4YZyDr1q/HCv1r1+3eA==
LastGistId=3a5294ce68996ba0fea18d8225a46695
LastGistUrl=https://gist.github.com/HaYToKoRaZ/3a5294ce68996ba0fea18d8225a46695
AutoGistOnStartup=True
AutoBackupOnStartup=True
MaxBackupCount=30

[🛡️ FullSafe]
Enabled=True
ExeLocation="C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"|True|True

[Diger]
Enabled=True
FolderLocation_1="C:\Program Files (x86)\dotnet"|True|True
FolderLocation_2="C:\Program Files (x86)\LightingService"|True|True
FolderLocation_3="C:\Program Files (x86)\Minimal ADB and Fastboot"|True|True
FolderLocation_4="C:\Program Files (x86)\QUALCOMM Incorporated"|True|True
FolderLocation_5="C:\Program Files (x86)\Qualcomm"|True|True
FolderLocation_6="C:\Program Files (x86)\Realtek"|True|True
FolderLocation_7="C:\Program Files (x86)\TP-Link"|True|True
FolderLocation_8="C:\Program Files (x86)\Xiaomi IMEI Tools"|True|True
FolderLocation_9="C:\Program Files\7-Zip"|True|True
FolderLocation_10="C:\Program Files\Easy Context Menu"|True|True
FolderLocation_11="C:\Program Files\MiniTool Partition Wizard 13"|True|True
FolderLocation_12="C:\Program Files\StartAllBack"|True|True
FolderLocation_13="C:\Program Files\SteelSeries"|True|True
FolderLocation_14="C:\Program Files\WindowsApps\Shapr3D.Shapr3D_5.730.7613.0_x64__dvv5p1vgwv6mp"|True|True
FolderLocation_15="C:\ProgramData\SteelSeries"|True|True
FolderLocation_16="D:\Program Files\aida64extreme"|True|True
FolderLocation_17="D:\Program Files\SoundVolumeView"|True|True
FolderLocation_18="D:\Program Files\TaskbarGroups"|True|True
FolderLocation_19="D:\Program Files\XB1ControllerBatteryIndicator_1.3.1.2"|True|True
FolderLocation_20="D:\Program Files\digiKam"|True|True
FolderLocation_21="C:\Program Files\ZALMAN-CVM"|True|True
FolderLocation_22="C:\Program Files\TeraCopy"|True|True

[Game]
Enabled=True
FolderLocation="G:\CrackGame"|True|True
